[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "copper_100"
requires-python = ">=3.7"
version = "0.0.1"
dependencies = [
    "numpy","matplotlib","scipy"
]

